# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
